#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-byteman
Version  : 3.0.3
Release  : 2
URL      : https://github.com/bytemanproject/byteman/archive/3.0.3.tar.gz
Source0  : https://github.com/bytemanproject/byteman/archive/3.0.3.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/jboss/byteman/byteman-bmunit/3.0.3/byteman-bmunit-3.0.3.jar
Source2  : https://repo.maven.apache.org/maven2/org/jboss/byteman/byteman-bmunit/3.0.3/byteman-bmunit-3.0.3.pom
Source3  : https://repo.maven.apache.org/maven2/org/jboss/byteman/byteman-install/3.0.3/byteman-install-3.0.3.jar
Source4  : https://repo.maven.apache.org/maven2/org/jboss/byteman/byteman-install/3.0.3/byteman-install-3.0.3.pom
Source5  : https://repo.maven.apache.org/maven2/org/jboss/byteman/byteman-root/3.0.3/byteman-root-3.0.3.pom
Source6  : https://repo.maven.apache.org/maven2/org/jboss/byteman/byteman-submit/3.0.3/byteman-submit-3.0.3.jar
Source7  : https://repo.maven.apache.org/maven2/org/jboss/byteman/byteman-submit/3.0.3/byteman-submit-3.0.3.pom
Source8  : https://repo.maven.apache.org/maven2/org/jboss/byteman/byteman/3.0.3/byteman-3.0.3.jar
Source9  : https://repo.maven.apache.org/maven2/org/jboss/byteman/byteman/3.0.3/byteman-3.0.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: mvn-byteman-data = %{version}-%{release}
Requires: mvn-byteman-license = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : buildreq-mvn

%description
--------------
Byteman supports injection of side effects into Java programs for the
purpose of tracing and testing application behaviour.

%package data
Summary: data components for the mvn-byteman package.
Group: Data

%description data
data components for the mvn-byteman package.


%package license
Summary: license components for the mvn-byteman package.
Group: Default

%description license
license components for the mvn-byteman package.


%prep
%setup -q -n byteman-3.0.3

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-byteman
cp docs/copyright.txt %{buildroot}/usr/share/package-licenses/mvn-byteman/docs_copyright.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jboss/byteman/byteman-bmunit/3.0.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/jboss/byteman/byteman-bmunit/3.0.3/byteman-bmunit-3.0.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jboss/byteman/byteman-bmunit/3.0.3
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/jboss/byteman/byteman-bmunit/3.0.3/byteman-bmunit-3.0.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jboss/byteman/byteman-install/3.0.3
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/jboss/byteman/byteman-install/3.0.3/byteman-install-3.0.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jboss/byteman/byteman-install/3.0.3
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/jboss/byteman/byteman-install/3.0.3/byteman-install-3.0.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jboss/byteman/byteman-root/3.0.3
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/jboss/byteman/byteman-root/3.0.3/byteman-root-3.0.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jboss/byteman/byteman-submit/3.0.3
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/jboss/byteman/byteman-submit/3.0.3/byteman-submit-3.0.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jboss/byteman/byteman-submit/3.0.3
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/jboss/byteman/byteman-submit/3.0.3/byteman-submit-3.0.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jboss/byteman/byteman/3.0.3
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/jboss/byteman/byteman/3.0.3/byteman-3.0.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jboss/byteman/byteman/3.0.3
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/jboss/byteman/byteman/3.0.3/byteman-3.0.3.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/jboss/byteman/byteman-bmunit/3.0.3/byteman-bmunit-3.0.3.jar
/usr/share/java/.m2/repository/org/jboss/byteman/byteman-bmunit/3.0.3/byteman-bmunit-3.0.3.pom
/usr/share/java/.m2/repository/org/jboss/byteman/byteman-install/3.0.3/byteman-install-3.0.3.jar
/usr/share/java/.m2/repository/org/jboss/byteman/byteman-install/3.0.3/byteman-install-3.0.3.pom
/usr/share/java/.m2/repository/org/jboss/byteman/byteman-root/3.0.3/byteman-root-3.0.3.pom
/usr/share/java/.m2/repository/org/jboss/byteman/byteman-submit/3.0.3/byteman-submit-3.0.3.jar
/usr/share/java/.m2/repository/org/jboss/byteman/byteman-submit/3.0.3/byteman-submit-3.0.3.pom
/usr/share/java/.m2/repository/org/jboss/byteman/byteman/3.0.3/byteman-3.0.3.jar
/usr/share/java/.m2/repository/org/jboss/byteman/byteman/3.0.3/byteman-3.0.3.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-byteman/docs_copyright.txt
